version: 2.1

orbs:

  node: circleci/node@4.1
jobs:
  run_tests:
    docker:
      - image: cimg/node:15.1
      - image: circleci/postgres:9.5-postgis
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_HOST: $POSTGRES_HOST
          POSTGRES_PORT: $POSTGRES_PORT

    steps:
      - checkout #alias for git clone\
      - node/install-packages
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run unit tests
          command: |
            npm run test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_test:
    jobs:
      - run_tests
